### ISSUE TITLE
Difference enhancements

### ISSUE THREAD

**Issue by smartmeter** [ivanovevgeny/HtmlAgilityPack#1]
Hello, thanks for this fork, does this have any enhancements over the base version.

**Comment by ivanovevgeny** [comment]
Hello! Just only one what i need in my project - https://github.com/ivanovevgeny/HtmlAgilityPack/commit/667a98174bd90882b0d6463d66765fde2eba51e9

**Comment by smartmeter** [comment]
what was the enhancements 
do you know where the latest version might be?
